name: TradeManager
main: me.maskat.TradeManager.Plugin
description: Trade Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

commands:
   trade:
      description: TradeManager command