name: MoneyManager
main: me.maskat.MoneyManager.Plugin
description: Money Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

permissions:
   mkp.moneymanager.doublepointsreward:
      default: op
      
#commands:
#  skypoints:
#    permission: mkp.moneymanager.skypoints.use