name: CustomCommand_MKProject
main: me.maskat.customcommand.Plugin
description: Custom Command
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

commands:
   konkurs:
      description: Custom Commands
   konkursreload:
      description: Custom Commands - Konkurs reload
      permission: mkp.customcommand.konkursreload
permissions:
   #/konkurs
   mkp.adminutils.konkurs.use:
      default: op
   mkp.adminutils.konkurs.allowworld.*:
      default: op
   mkp.adminutils.konkurs.allowgamemode.*:
      default: op
   mkp.adminutils.konkurs.dolacz.use:
      default: op