name: SpecialTools_MKProject
main: mkproject.maskat.SpecialTools.Plugin
description: Special Tools
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]
