
MySQL:
   Hostname: 'localhost'
   Port: '6603'
   Username: 'minecraft_server'
   Password: 'password'
   Database: 'minecraft_gildie'
   SSL: True
   DebugConsole: True

# Time is in secounds!

Player:
   CheckAfkStatusTime: 30
   GoAfkAfterTime: 60
   
Server:
   LobbyWorldName: world_lobby
   SpawnWorldName: world_spawncenter
   SurvivalWorldName: world

Plugin:
   UseWorldEdit: true
   UseVault: true
