name: InventoryManager
main: me.maskat.InventoryManager.Plugin
description: Inventory Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

#commands:
#   c:
#      description: Custom Commands
#permissions:
#   mkp.customcommand.*:
#      description: Allows use custom commands
#      default: op