name: CmdBlockAdvancedManager
main: mkproject.maskat.CmdBlockAdvancedManager.Plugin
description: CommandBlock Advanced Manager by MKProject
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

commands:
  cmdblockadvancedmanager:
    description: Reload the configuration
    permission: mkp.cmdblockadvancedmanager.usecommand
    aliases: [cb, cba, cbam]

#permissions:
#   mkp.cmdblockadvancedmanager.adminchat.send:
#      description: Allows use Admin Chat
#      default: op