name: LoginManager
main: mkproject.maskat.LoginManager.Plugin
description: Login Manager by MKProject
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]
softdepend: [MenuHelpManager,InventoryManager]

commands:
  loginmanager:
    description: Reload the configuration
    permission: mkp.loginmanager.reload
    usage: "Did you mean to run '/loginmanager reload'?"
  login:
    description: Player login
    aliases: l
  register:
    description: Player register
    aliases: reg
  changepassword:
    description: Player change password
    aliases: changepass

permissions:
   mkp.loginmanager.abortremoveexpwhenjoineddead:
      description: Abort remove EXP when joined dead
      default: op
   mkp.loginmanager.bypass.jointosafelastlocation:
      description: Abort remove EXP when joined dead
      default: op
   mkp.loginmanager.bypass.gamemode:
      description: Abort remove EXP when joined dead
      default: op
   mkp.loginmanager.info.multiaccount:
      description: Player multiaccount info when logged
      default: op