
MySQL:
   Table:
      Users: 'MKP_LoginManager_Users'
      Users_Logs: 'MKP_LoginManager_Logs'

# Time is in secounds!

Games:
#   ColorMix:
#      Worlds:
#         world_colormix:
#            PlayersNeed: 5
#            PlayersMax: 20
#            Platform:
#               Default:
#                  World: world_colormix_default
#                  X1: -25
#                  Y1: 75
#                  Z1: 10
#                  X2: -18
#                  Y2: 75
#                  Z2: 1
#               Play:
#                  X1: -30
#                  Y1: 100
#                  Z1: 20
#   Sumo:
#      Worlds:
#         world_sumo:
#            PlayersNeed: 5
#            PlayersMax: 20
#            Platform:
#               Play:
#                  Y: 100