name: QuestManager
main: me.maskat.QuestManager.Plugin
description: Quest Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]
softdepend: [MoneyManager]
