name: PortalManager
main: mkproject.maskat.PortalManager.Plugin
description: Portal Manager by MKProject
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI,WorldEdit,SpawnManager]

commands:
   portalmanager:
      description: Portal Manager command for Admins
permissions:
   mkp.portalmanager.admin:
      description: Allows use /portalmanager
      default: op