name: AdminUtils
main: mkproject.maskat.AdminUtils.Plugin
description: Admin Utils
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI,CommandAPI]
softdepend: [LoginManager,SpawnManager]

commands:
   tpposition:
      description: AdminUtils command
      aliases: tppos
   tphere:
      description: AdminUtils command
   inventory:
      description: AdminUtils command
      aliases: inv
   gm:
      description: AdminUtils command
   head:
      description: AdminUtils command
   fly:
      description: AdminUtils command
   speed:
      description: AdminUtils command
   repair:
      description: AdminUtils command
   back:
      description: AdminUtils command
   feed:
      description: AdminUtils command
   heal:
      description: AdminUtils command
   time:
      description: AdminUtils command
   playerinfo:
      description: AdminUtils command
      aliases: [pinfo]
   playerhistory:
      description: AdminUtils command
      aliases: [phistory]
   mute:
      description: AdminUtils command
   unmute:
      description: AdminUtils command
   kick:
      description: AdminUtils command
   ban:
      description: AdminUtils command
   banoffline:
      description: AdminUtils command
   unban:
      description: AdminUtils command
   tpworld:
      description: AdminUtils command
   top:
      description: AdminUtils command
   respawn:
      description: AdminUtils command
   bed:
      description: AdminUtils command
   spawn:
      description: AdminUtils command
   near:
      description: AdminUtils command
   randomtp:
      description: AdminUtils command
      aliases: [rtp]
   plugin:
      description: AdminUtils command
   titletext:
      description: AdminUtils command
   eventspawnchestitems:
      description: AdminUtils command
   chat:
      description: AdminUtils command
   collision:
      description: AdminUtils command
   survival:
      description: AdminUtils command
   rename:
      description: AdminUtils command
   enderchest:
      description: AdminUtils command
      aliases: [ec]
      
      
      
permissions:
   #/tppos <X> [Y] <Z> [world]
   mkp.adminutils.tppos.use:
      default: op
   mkp.adminutils.tppos.allowworld.*:
      default: op
   mkp.adminutils.tppos.allowgamemode.*:
      default: op
   mkp.adminutils.tppos.otherworld:
      default: op
   
   
   #/tphere <player>
   mkp.adminutils.tphere.use:
      default: op
   mkp.adminutils.tphere.allowworld.*:
      default: op
   mkp.adminutils.tphere.allowgamemode.*:
      default: op
   mkp.adminutils.tphere.otherplayer:
      default: op
   
   
   #/inventory see|get|set|clear <[player]>
   mkp.adminutils.inventory.use:
      default: op
   mkp.adminutils.inventory.allowworld.*:
      default: op
   mkp.adminutils.inventory.allowgamemode.*:
      default: op
      
   mkp.adminutils.inventory.see.use:
      default: op
   mkp.adminutils.inventory.see.otherplayer:
      default: op
   mkp.adminutils.inventory.get.use:
      default: op
   mkp.adminutils.inventory.get.otherplayer:
      default: op
   mkp.adminutils.inventory.set.use:
      default: op
   mkp.adminutils.inventory.set.otherplayer:
      default: op
   mkp.adminutils.inventory.clear.use:
      default: op
   mkp.adminutils.inventory.clear.otherplayer:
      default: op
   
   
   #/gm 0|1|2|3 [player]
   mkp.adminutils.gm.use:
      default: op
   mkp.adminutils.gm.allowworld.*:
      default: op
   mkp.adminutils.gm.allowgamemode.*:
      default: op
      
   mkp.adminutils.gm.survival.use:
      default: op
   mkp.adminutils.gm.survival.otherplayer:
      default: op
   mkp.adminutils.gm.creative.use:
      default: op
   mkp.adminutils.gm.creative.other:
      default: op
   mkp.adminutils.gm.adventure.otherplayer:
      default: op
   mkp.adminutils.gm.adventure.use:
      default: op
   mkp.adminutils.gm.spectator.use:
      default: op
   mkp.adminutils.gm.spectator.otherplayer:
      default: op
   
   
   #/head <headname> [player]
   mkp.adminutils.head.use:
      default: op
   mkp.adminutils.head.allowworld.*:
      default: op
   mkp.adminutils.head.allowgamemode.*:
      default: op
      
   mkp.adminutils.head.otherplayer:
      default: op
      
      
   #/fly 0|1 [player]
   mkp.adminutils.fly.use:
      default: op
   mkp.adminutils.fly.allowworld.*:
      default: op
   mkp.adminutils.fly.allowgamemode.*:
      default: op
   mkp.adminutils.fly.otherplayer:
      default: op
      
      
   #/collision 0|1 [player]
   mkp.adminutils.fly.use:
      default: op
   mkp.adminutils.fly.allowworld.*:
      default: op
   mkp.adminutils.fly.allowgamemode.*:
      default: op
   mkp.adminutils.fly.otherplayer:
      default: op
      
      
   #/speed 0-5 [player]
   mkp.adminutils.speed.use:
      default: op
   mkp.adminutils.speed.allowworld.*:
      default: op
   mkp.adminutils.speed.allowgamemode.*:
      default: op
      
   mkp.adminutils.speed.otherplayer:
      default: op
      
      
   #/repair [player]
   mkp.adminutils.repair.use:
      default: op
   mkp.adminutils.repair.allowworld.*:
      default: op
   mkp.adminutils.repair.allowgamemode.*:
      default: op
   mkp.adminutils.repair.otherplayer:
      default: op
      
      
   #/back [player]
   mkp.adminutils.back.use:
      default: op
   mkp.adminutils.back.allowworld.*:
      default: op
   mkp.adminutils.back.allowgamemode.*:
      default: op
   mkp.adminutils.back.otherplayer:
      default: op
      
      
   #/feed [player]
   mkp.adminutils.feed.use:
      default: op
   mkp.adminutils.feed.allowworld.*:
      default: op
   mkp.adminutils.feed.allowgamemode.*:
      default: op
   mkp.adminutils.feed.otherplayer:
      default: op
      
      
   #/heal [player]
   mkp.adminutils.heal.use:
      default: op
   mkp.adminutils.heal.allowworld.*:
      default: op
   mkp.adminutils.heal.allowgamemode.*:
      default: op
   mkp.adminutils.heal.otherplayer:
      default: op
      
      
   #/respawn [player]
   mkp.adminutils.respawn.use:
      default: op
   mkp.adminutils.respawn.allowworld.*:
      default: op
   mkp.adminutils.respawn.allowgamemode.*:
      default: op
   mkp.adminutils.respawn.otherplayer:
      default: op
      
      
   #/time day|noon|night|midnight|0-24000 [world]
   mkp.adminutils.time.use:
      default: op
   mkp.adminutils.time.allowworld.*:
      default: op
   mkp.adminutils.time.allowgamemode.*:
      default: op
   mkp.adminutils.time.otherworld:
      default: op
      
      
   #/playerinfo [player] | /pinfo [player]
   mkp.adminutils.playerinfo.use:
      default: op
   mkp.adminutils.playerinfo.allowworld.*:
      default: op
   mkp.adminutils.playerinfo.allowgamemode.*:
      default: op
   mkp.adminutils.playerinfo.otherplayer:
      default: op
      
   #/playerhistory [player] [page] | /phistory [player] [page]
   mkp.adminutils.playerhistory.use:
      default: op
   mkp.adminutils.playerhistory.allowworld.*:
      default: op
   mkp.adminutils.playerhistory.allowgamemode.*:
      default: op
      
      
   #/mute <player> <time> <timeformat> [reason]
   mkp.adminutils.mute.use:
      default: op
   mkp.adminutils.mute.allowworld.*:
      default: op
   mkp.adminutils.mute.allowgamemode.*:
      default: op
   mkp.adminutils.mute.otherplayer:
      default: op
   mkp.adminutils.mute.immunitet:
      default: op
      
      
   #/unmute <player> [reason]
   mkp.adminutils.unmute.use:
      default: op
   mkp.adminutils.unmute.allowworld.*:
      default: op
   mkp.adminutils.unmute.allowgamemode.*:
      default: op
   mkp.adminutils.unmute.otherplayer:
      default: op
       
            
   #/kick <player|*> [reason]
   mkp.adminutils.kick.use:
      default: op
   mkp.adminutils.kick.all.use:
      default: op
   mkp.adminutils.kick.allowworld.*:
      default: op
   mkp.adminutils.kick.allowgamemode.*:
      default: op
   mkp.adminutils.kick.otherplayer:
      default: op
   mkp.adminutils.kick.immunitet:
      default: op
      
   #/ban <player> <time|perm> [timeformat] [reason]
   mkp.adminutils.ban.use:
      default: op
   mkp.adminutils.ban.allowworld.*:
      default: op
   mkp.adminutils.ban.allowgamemode.*:
      default: op
   mkp.adminutils.ban.otherplayer:
      default: op
   mkp.adminutils.ban.immunitet:
      default: op
      
   #/banoffline <player> <time|perm> [timeformat] [reason]
   mkp.adminutils.banoffline.use:
      default: op
   mkp.adminutils.banoffline.allowworld.*:
      default: op
   mkp.adminutils.banoffline.allowgamemode.*:
      default: op
      
      
   #/unban <player> [reason]
   mkp.adminutils.unban.use:
      default: op
   mkp.adminutils.unban.allowworld.*:
      default: op
   mkp.adminutils.unban.allowgamemode.*:
      default: op
   mkp.adminutils.unban.otherplayer:
      default: op
      
      
   #/tpworld <world> [player]
   mkp.adminutils.tpworld.use:
      default: op
   mkp.adminutils.tpworld.allowworld.*:
      default: op
   mkp.adminutils.tpworld.allowgamemode.*:
      default: op
   mkp.adminutils.tpworld.otherplayer:
      default: op
   mkp.adminutils.tpworld.otherworld:
      default: op
   mkp.adminutils.tpworld.accessworld.*:
      default: op
      

   #/top <amount>
   mkp.adminutils.top.use:
      default: op
   mkp.adminutils.top.allowworld.*:
      default: op
   mkp.adminutils.top.allowgamemode.*:
      default: op
      
      
   #/bed <player>
   mkp.adminutils.bed.use:
      default: op
   mkp.adminutils.bed.allowworld.*:
      default: op
   mkp.adminutils.bed.allowgamemode.*:
      default: op
   mkp.adminutils.bed.otherplayer:
      default: op
   mkp.adminutils.bed.bypass.payment:
      default: op
      

   #/spawn
   mkp.adminutils.spawn.use:
      default: op
   mkp.adminutils.spawn.allowworld.*:
      default: op
   mkp.adminutils.spawn.allowgamemode.*:
      default: op
   mkp.adminutils.survival.otherplayer.*:
      default: op
      

   #/survival
   mkp.adminutils.survival.use:
      default: op
   mkp.adminutils.survival.allowworld.*:
      default: op
   mkp.adminutils.survival.allowgamemode.*:
      default: op
   mkp.adminutils.survival.otherplayer.*:
      default: op
      

   #/near [player] [range]
   mkp.adminutils.near.use:
      default: op
   mkp.adminutils.near.allowworld.*:
      default: op
   mkp.adminutils.near.allowgamemode.*:
      default: op
   mkp.adminutils.near.otherplayer:
      default: op
      

   #/randomtp /rtp
   mkp.adminutils.randomtp.use:
      default: op
   mkp.adminutils.randomtp.allowworld.*:
      default: op
   mkp.adminutils.randomtp.allowgamemode.*:
      default: op
      
      
   #/plugin list|restart|enable|disable <[plugin]>
   mkp.adminutils.plugin.use:
      default: op
   mkp.adminutils.plugin.allowworld.*:
      default: op
   mkp.adminutils.plugin.allowgamemode.*:
      default: op
      
      
   #/titletext <player|*> <<title>%nl%<subtitle>>
   mkp.adminutils.titletext.use:
      default: op
   mkp.adminutils.titletext.allowworld.*:
      default: op
   mkp.adminutils.titletext.allowgamemode.*:
      default: op
   mkp.adminutils.titletext.otherplayer:
      default: op
      
      
      
   #/eventspawnchestitems
   mkp.adminutils.eventspawnchestitems.use:
      default: op
   mkp.adminutils.eventspawnchestitems.allowworld.*:
      default: op
   mkp.adminutils.eventspawnchestitems.allowgamemode.*:
      default: op
      
      
   #/chat clear
   mkp.adminutils.chat.use:
      default: op
   mkp.adminutils.chat.allowworld.*:
      default: op
   mkp.adminutils.chat.allowgamemode.*:
      default: op
   mkp.adminutils.chat.clear.use:
      default: op
      
      
   #/collision 0|1 [player]
   mkp.adminutils.collision.use:
      default: op
   mkp.adminutils.collision.allowworld.*:
      default: op
   mkp.adminutils.collision.allowgamemode.*:
      default: op
   mkp.adminutils.collision.otherplayer.*:
      default: op
      
      
   #/rename name|lore <new_item_name>
   mkp.adminutils.rename.use:
      default: op
   mkp.adminutils.rename.allowworld.*:
      default: op
   mkp.adminutils.rename.allowgamemode.*:
      default: op
      
      
      
   #/skypoints set|add|remove <value>
   mkp.adminutils.skypoints.use:
      default: op
      
   
   #/enderchest [player]
   mkp.adminutils.enderchest.use:
      default: op
   mkp.adminutils.enderchest.allowworld.*:
      default: op
   mkp.adminutils.enderchest.allowgamemode.*:
      default: op
   mkp.adminutils.enderchest.otherplayer.*:
      default: op
      
      
      
      