ResetTheEnd:
   Price: 1000
   LastReset:
      DateTime: ''
      PlayerName: ''

categories:
   ZoneVipPlus:
   
   Kopalnia:
      name: "Kopalnia"
      icon: "DIAMOND_ORE"
      description: "Diamenty, żelazo, złoto itp."
      items:
         1:
            item: EMERALD
            buy: 500000000
            sell: 100000
         infinity1:
            item: ENCHANTED_BOOK
            enchants:
               infinity: 1
            buy: 200000000
            sell: 100000

            
            
            