name: CompassPoint
main: me.maskat.compasspoint.Plugin
description: Compass Point
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [Parties, WolfSecurity, MKProjectAPI]

permissions:
   mkp.compasspoint.bypass.anotherthan.world:
      description: Allows select point in another worlds than map name - world 
      default: op