name: ShopManager
main: me.maskat.ShopManager.Plugin
description: Shop Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]
softdepend: [MoneyManager]

commands:
   shopmanager:
      description: Reload the configuration
      permission: mkp.shopmanager.reload
      usage: "Did you mean to run '/shopmanager reload'?"
   shop:
      description: ShopManager command
      aliases: [sklep,targ,targowisko]
permissions:
   mkp.shopmanager.*:
      description: Allows use custom commands
      default: op
   mkp.shopmanager.vip:
      description: Allows use vip price in promo
      default: op
   mkp.shopmanager.svip:
      description: Allows use vip price in all
      default: op
   mkp.shopmanager.vipzone:
      description: Access to vip zone
      default: op