# LandSecurity plugin for 1.15.2
# Made by MasKAT

database:
   host: '192.168.1.10'
   port: '6736'
   user: 'minecraft_server'
   password: '69Uri6Us4cSnpZ0W'
   database: 'minecraft_server'
   ssl: True
   table:
      regions: "wolfsecurity_s1_regions"
      users: "wolfsecurity_s1_users"
      wolves: "wolfsecurity_s1_wolves"