# LandSecurity plugin for 1.15.2
# Made by MasKAT

database:
   host: '127.0.0.1'
   port: '6736'
   user: 'minecraft_server'
   password: '69Uri6Us4cSnpZ0W'
   database: 'minecraft_server116'
   ssl: True
   table:
      regions: "MKP_WolfSecurity_Regions"
      users: "MKP_WolfSecurity_Users"
      wolves: "MKP_WolfSecurity_Wolves"