name: WolfSecurity
main: me.maskat.wolfsecurity.Plugin
description: Wolf Security by MKProject
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
softdepend: [AuthMe, ProtocolLib, Vault, CoreProtect]
depend: [MKProjectAPI]

commands:
  wolf:
    description: Command wolf
    aliases: [wilk]
    
permissions:
  mkp.wolfsecurity.region.protect:
    description: Protect wolf region
    default: op