name: DropManager
main: mkproject.maskat.DropManager.Plugin
description: Drop Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]

commands:
  dropmanager:
    description: Reload the configuration
    permission: mkp.dropmanager.reload
    usage: "Did you mean to run '/dropmanager reload'?"