name: LoginManager
main: mkproject.maskat.LoginManager.Plugin
description: Login Manager by MKProject
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD
depend: [MKProjectAPI]
softdepend: [MenuHelpManager]

commands:
  loginmanager:
    description: Reload the configuration
    permission: mkp.loginmanager.reload
    usage: "Did you mean to run '/loginmanager reload'?"
  login:
    description: Player login
    aliases: l
  register:
    description: Player register
    aliases: reg

#permissions:
#   mkp.chatmanager.adminchat.access:
#      description: Allows use Admin Chat
#      default: op