name: WorldManager
main: mkproject.maskat.WorldManager.Plugin
description: World Manager
version: 1.0.0
author: MasKAT
website: http://skyidea.pl/
api-version: 1.15
load: POSTWORLD

commands:
  worldmanager:
    description: Reload the configuration
    permission: mkp.worldmanager.reload
    usage: "Did you mean to run '/worldmanager reload'?"
    
permissions:
   mkp.worldmanager.bypass.gamemode:
      description: Bypass for gamemode switch when player teleport between worlds
      default: op
